### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by rickyngk** [telepat-io/telepat-js#7]
I'm using telepat 0.2.2 via docker image. I use the following code to connect my web-app (run on localhost:3000 - using gulp) to backend (192.168.99.100:3000)

    Telepat = new Telepat();
    Telepat.on('connect', function () {
     });
    Telepat.connect({
        apiKey: "49d0696cda74dbfb89799b08ffbf2443",
        appId: 1,
        apiEndpoint: "192.168.99.100:3000",
        socketEndpoint: "192.168.99.100:3000"
    })

And got issue
    
    XMLHttpRequest cannot load http://192.168.99.100:3000/socket.io/?EIO=3&transport=polling&t=1442829019967-2. A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'http://localhost:3000' is therefore not allowed access.

Would you plz give me a hint?

**Comment by Mayhem93** [comment]
Which browser are you using ?

@gabidobo Have a look here

**Comment by gabidobo** [comment]
@rickyngk I'm guessing that's because you're accessing the socket.io server on port 3000 - it should be 80. Can you try to `socketEndpoint: "192.168.99.100"` instead?

**Comment by rickyngk** [comment]
@gabidobo :+1:  Yes, you are right. Correct config should be
    
    Telepat = new Telepat();
    Telepat.on('connect', function () {
     }); 
    Telepat.connect({
        apiKey: "49d0696cda74dbfb89799b08ffbf2443",
        appId: 1,
        apiEndpoint: "http://192.168.99.100:3000",
        socketEndpoint: "192.168.99.100"
    })
